### ISSUE TITLE
'SigMeshOC/SDKLibCommand.h' file not found

### ISSUE THREAD

**Issue by chuga2310** [flyskywhy/react-native-btsig-telink#2]
I tried to import your lib into my Project.
But when i build for ios, i got a bug. Please check and support me if you can.
`'SigMeshOC/SDKLibCommand.h' file not found`

**Comment by flyskywhy** [comment]
As README.md said:

Open `SigMeshOC/SigMeshOC.xcodeproj` by Xcode, in 'Signing & Capabilities' of Target 的 'SigMeshOC', choose `Team` to your Apple ID, then close Xcode and:

    cd node_modules/react-native-btsig-telink/SigMeshOC/
    ./Script.sh

results:
```
SigMeshOC/Build/Products/SigMeshOC/Release-iphoneos/SigMeshOC.framework/
```
