### ISSUE TITLE
设备断连后如何重新连接呢

### ISSUE THREAD

**Issue by louisV7** [flyskywhy/react-native-btsig-telink#5]
在配网成功之后，当我给蓝牙模块重新断点供电后，我调用autoconnect方法能够重新正常控制设备
但当我重启app之后再调用autoconnect也不能恢复网络，请问应该如何做呢？

**Comment by louisV7** [comment]
我在index.native.js中找到了原因，因为没有给devices赋值，默认是空数组，我新增了一个setDevices方法来给devices赋值
`
  static setDevices(deviceList) {
    this.devices = deviceList;
    this.doInit();
  };
`
设备入网之后将设备信息存入storage,在APP create时我读取storage中的deviceList并且调用setDevices方法和autoconnect方法。
但是当autoconnect的逻辑跑到 android/src/main/java/com/telink/sig/mesh/event/EventBus.java 中 processOnThread()方法时，会在146行
`            case Default:
                mCurrentThreadHandler.post(task);
                break;
`这个post方法时发生闪退。如果注释这个post就能正常重连设备，但是我觉得这是不对的。
而如果我是配网完成后不重启APP，也就是没有去setDevices时，调用autoconnect时这里就不会发生闪退，请问再重启APP后正确的重连设备方法是如何操作呢？感谢。

**Comment by flyskywhy** [comment]
不好意思，我一般写文档都很详细的，但是这个组件牵扯的东西太多，就算能在 `README.md` 写很多也可能适得其反，所以只好麻烦你们使用人员自己翻阅 telink 官方文档和 `README.md` 提到的 `index.native.js` 了。
所以，现在问题解决了吗？
在 `this.doInit()` 之前，除了你发现 :+1:  的自己存储、读取 storage 然后给 devices 赋值外，同样需要赋值的还有 netKey 、 appKey 和 provisionerSno

重启 APP 后无法重连的问题当初也困扰了我很久，不过倒是没有碰到 post 方法导致的闪退问题，后来发现是需要在重启 APP 时恢复 provisionerSno （抱歉，这几天太忙没有上 github 没有及时回复，不知你自己解决了没 :stuck_out_tongue_closed_eyes: ）

`react-native-btsig-telink/android/src/main/java/com/telink/sig/mesh/TelinkBtSigNativeModule.java` 中的 `case MeshEvent.EVENT_TYPE_AUTO_CONNECT_LOGIN:` 处会调用 `saveOrUpdateJS()` ，另外在 `react-native-btsig-telink/android/src/main/java/com/telink/sig/mesh/TelinkApplication.java` 中的 `onMeshInfoUpdate()` 处也会调用 `saveOrUpdateJS()` ，里面会发出 `saveOrUpdateJS` 的 JS 事件，这就是你的 APP 更新保存 provisionerSno 的时机。

**Comment by louisV7** [comment]
感谢回复
这个问题解决了，
闪退是因为配网返回值里面没有macaddress和meshaddress的原因，调用autoconnect之后sdk跑到那个post后面逻辑应该没有找到macaddress导致闪退了，我自己存储之后自己加了进去就可以了。
不过我看到index.native.js中封装了关于group的配置接口，却没有相应的控制接口，telink的app中group可以控制onoff，这个组件是需要自己封装一个group控制接口然后调用sendMeshMessage吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Li ***@***.***&gt;; 
发送时间: 2022年7月21日(星期四) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [flyskywhy/react-native-btsig-telink] 设备断连后如何重新连接呢 (Issue #5)





 
不好意思，我一般写文档都很详细的，但是这个组件牵扯的东西太多，就算能在 README.md 写很多也可能适得其反，所以只好麻烦你们使用人员自己翻阅 telink 官方文档和 README.md 提到的 index.native.js 了。
 所以，现在问题解决了吗？
 在 this.doInit() 之前，除了你发现 👍  的自己存储、读取 storage 然后给 devices 赋值外，同样需要赋值的还有 netKey 、 appKey 和 provisionerSno
 
重启 APP 后无法重连的问题当初也困扰了我很久，不过倒是没有碰到 post 方法导致的闪退问题，后来发现是需要在重启 APP 时恢复 provisionerSno （抱歉，这几天太忙没有上 github 没有及时回复，不知你自己解决了没 😝 ）
 
react-native-btsig-telink/android/src/main/java/com/telink/sig/mesh/TelinkBtSigNativeModule.java 中的 case MeshEvent.EVENT_TYPE_AUTO_CONNECT_LOGIN: 处会调用 saveOrUpdateJS() ，另外在 react-native-btsig-telink/android/src/main/java/com/telink/sig/mesh/TelinkApplication.java 中的 onMeshInfoUpdate() 处也会调用 saveOrUpdateJS() ，里面会发出 saveOrUpdateJS 的 JS 事件，这就是你的 APP 更新保存 provisionerSno 的时机。

**Comment by flyskywhy** [comment]
不用自己封装。以

    changePower({
        meshAddress,
        ...
    })

为例，只要在 meshAddress 参数中传入 groupAddress 的值即可

**Comment by louisV7** [comment]
查了资料，groupAddress是要求C0开头..然后meshAddress最大是7FFF。然后，这些东西 tenlink写在了上位机的操作手册里面的...太坑了...
最后一个问题就是，如果我想实现自定义的功能，拟订了私有协议，不以默认的a3ff开头这种，这个组件能够实现吗，上位机是可以发，我不知道这个组件能发不

**Comment by flyskywhy** [comment]
这个组件的 `index.native.js` 中的 `sendCommand` 实现的自定义功能是 telink 官方提供给客户的自定义功能，比如我们自定义的关灯功能，`sendCommand(0x0211E0` 实际发送的是 `a3 ff 00 00 00 00 02 00  ff ff e0 11 02 e3 02 00` ，从中可以看到 `0x0211E0` 变成了 `e0 11 02` （当然对应固件也要修改成能够处理 `0xe0` ） ，然后按照 `react-native-btsig-telink@1.3` 的 `android/src/main/java/com/telink/sig/mesh/util/MeshUtils.java` 中 `getOpType(int opVal)` 处的注释
```
    /**
     * Mesh V1.0 3.7.3.1 Operation codes
     * Opcode Format
     * Notes
     * 0xxxxxxx (excluding 01111111)
     * 1-octet Opcodes
     * 01111111
     * Reserved for Future Use
     * 10xxxxxx xxxxxxxx
     * 2-octet Opcodes
     * 11xxxxxx zzzzzzzz
     * 3-octet Opcodes
     */
```
`0xe0` 就符合 `11xxxxxx` 也就是给客户用的 VENDOR 命令类型。

你如果一定想要自定义 `a3ff` 开头的话你得自己去修改 `react-native-btsig-telink@1.3` 的 `android/src/main/java/com/telink/sig/mesh/model/MeshCommand.java` 中的 `HCI_CMD_BULK_CMD2DEBUG = 0xFFA3` （以及对应的固件），我很好奇你们是什么样的自定义而需要做这样的修改呢？

**Comment by louisV7** [comment]
在灯上接了一个雷达，实现检测人活动亮灯，没人就灭灯，这里就需要设置一个无人时间，没人了多久才会关掉灯，所以我们自己自定义了私有的协议
