### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by louisV7** [flyskywhy/react-native-btsig-telink#6]
1. rn的监听器已经弃用了Emitter.removeListener，应该使用listener.remove()；我使用子类继承重写了监听方法。
2. 建议在scan中加上rssi,搜索结果可以以此排序确定设备大概远近，我我自己在TelinkBtSigNativeModule中添加了
` params.putInt("rssi", advDevice.rssi);`

![Screenshot_20220901-164556](https://user-images.githubusercontent.com/14191238/187872998-ea649a8c-5680-429d-9b32-af47b8c41e19.jpg)
另外有个比较困惑的地方 关于APPKEY和NETKEY的长度
telink的APP中使用的appkey和netkey的32长度的字符串，
当我尝试使用相同的appkey和netkey时会报错 我将MeshKeystorage.java中的长度16的判断改为32后能够正常入网和控制
但一旦重启APP就无法再次连接设备

当我使用长度为16的字符串(eg:3d48d27ac363e2a2)作为netkey时能够正常使用和重连，我不知道这是为什么......

**Comment by flyskywhy** [comment]
`rn的监听器已经弃用了Emitter.removeListener，应该使用listener.remove()；` 是在最新的 RN 比如 0.69 做了更改吗？

rssi 我会考虑在后续版本中加入，谢谢！

32? 每 2 个字符代表一个 16 进制字符吧？所以还是 16 吧？

**Comment by louisV7** [comment]
> `rn的监听器已经弃用了Emitter.removeListener，应该使用listener.remove()；` 是在最新的 RN 比如 0.69 做了更改吗？
> 
> rssi 我会考虑在后续版本中加入，谢谢！
> 
> 32? 每 2 个字符代表一个 16 进制字符吧？所以还是 16 吧？

我使用的是0.66版本 会提示removeListener已经弃用
32这个 我开始也认为是2字符是代表一个16进制 但实际上你在TelinkBtSigNativeModule 的doInit方法中使用了
`
mNetKey = Strings.stringToBytes(netKey);
`
`
  mAppKey = Strings.stringToBytes(appKey);
`
实际上是直接将字符串转换为了bytes 这里1字符=1字节 我查阅了tenlink安卓版本的源码，他使用
`
            meshInfo.meshNetKeyList.add(new MeshNetKey(NET_KEY_NAMES[i], i,
                    Arrays.hexToBytes("12F08D8C4D071A15D2492BEEE628AF0E")));
`
`
            meshInfo.appKeyList.add(new MeshAppKey(APP_KEY_NAMES[i],
                    i,
                    Arrays.hexToBytes("B22AEFE003E7FE09662020D6CBC5E76E"),
                    i));
`
所以我认为应该改为 Arrays.hexToBytes(netKey/appKey) 不过因为代码中引用了java的Arrays 我不知道如何正确引入telink的Arrays工具类，所以我直接改成了如下，这样就和telink的APP中的KEY长度一致了
`
        mNetKey = com.telink.sig.mesh.util.Arrays.hexToBytes(netKey);
`
`
        mAppKey = com.telink.sig.mesh.util.Arrays.hexToBytes(appKey);
`

**Comment by louisV7** [comment]
另外我需要在android/build.gradle中加入
`implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'`
否则会报错 Failed resolution of: Landroid/support/v4/content/LocalBroadcastManager
根据我在网上找到的说法
`这个错误主要是LocalBroadcastManager这个类被弃用了，但是呢，在使用mqtt依赖库的时候又用到了这个类，所以导致这个类找不到。此时，就需要在build.gradle文件里添加依赖库了。`
我不知道这个问题是否具有通用性 所以只是顺带提及

**Comment by flyskywhy** [comment]
react-native-btsig-telink@2.0.0 添加了 rssi ，而且不再使用 LocalBroadcastManager

react-native-btsig-telink@2.0.0 将 telink sdk 从 3.1.0 升级到了 3.3.3.5

Arrays.hexToBytes 函数源码表明，它就是将 2 个字符转换为 1 个字节，所以就是在将 32 个字符转换为 16 字节的 key 。 telink 的代码之所以这样做，是因为它将 key 保存为了 32 字符（且每个字符只能在 0~F 之间取值）的字符串。我的 Strings.stringToBytes(appKey) 是将 1 个字符转换为 1 个字节，我之所以这样做，是因为我将 key 保存为了 16 字符（且每个字符可以是任意 ascii 字符）的字符串。
