### ISSUE TITLE
FOTA Compatibility

### ISSUE THREAD

**Issue by tamirrahamim29** [flyskywhy/react-native-btsig-telink#7]
Hey :)
I wanted to know whether this module supports FOTA.
Besides  - an enormous Kudos for your great job so far!

**Comment by flyskywhy** [comment]
Can `startOta()` one device one time.

If want `startMeshOTA()`, please ref to the comment of  https://github.com/flyskywhy/react-native-btsig-telink/blob/23e999558924ea1c1002f3a26e493206c3926f25/index.native.js#L221

I'm glad this repo is helpful :yum:

**Comment by tamirrahamim29** [comment]
Thank you for the quick answer Li :)
You're doing genuine, important work!
It's well appreciated.
